---
memory: 2048
cpus: 1
hostname: homeassistant.local
use_dhcp: false
ip_address: 192.168.1.15
netmask: 255.255.255.0
gateway_ip: 192.168.1.1
bridge: ~
post_up_message: Hass.io starting... wait a couple of minutes!
box: ubuntu/focal64
keep_config: true
shares:
  addons: /usr/share/hassio/addons/local
  backup: /usr/share/hassio/backup
  config: /usr/share/hassio/homeassistant
  share: /usr/share/hassio/share
  ssl: /usr/share/hassio/ssl
  
